### ISSUE TITLE
 pycloudsigma under python3.8 requires the "future" module

### ISSUE THREAD

**Issue by tpo** [cloudsigma/pycloudsigma#15]
```
Traceback (most recent call last):
  File "/usr/local/bin/vmcloudsigma.py", line 659, in <module>
    sys.exit(main())
  File "/usr/local/bin/vmcloudsigma.py", line 643, in main
    pycloudsigma = init_pycloudsigma(libcloud_driver)
  File "/usr/local/bin/vmcloudsigma.py", line 82, in init_pycloudsigma
    import cloudsigma
  File "/usr/local/lib/python3.8/dist-packages/cloudsigma/__init__.py", line 2, in <module>
    from cloudsigma import bulk
  File "/usr/local/lib/python3.8/dist-packages/cloudsigma/bulk.py", line 6, in <module>
    from .resource import Drive, Server, LibDrive
  File "/usr/local/lib/python3.8/dist-packages/cloudsigma/resource.py", line 5, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

**Comment by tpo** [comment]
I see that the "future" module is listed in the requirements, thus I'm closing this report. Thanks.
